Added merchant from prima
receipt-project/receipt-java pull request #31
Opened 2020-05-01 22:51 UTC by VladNesterov

2020-05-01 23:27 UTC, vladimirshefer requested changes

2020-05-01 23:27 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/service/MerchantService.kt
> +    lateinit var suggestion: MerchantWebclient
имя переменной не соответтсует ее смыслу

2020-05-01 23:27 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/MerchantWebclient.kt
> +class MerchantWebclient {
назови PrimaInformWebClient

2020-05-01 23:27 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/MerchantWebclient.kt
> +    fun getMerchantFromPrimaInformOrNone(inn: String): MerchantSuggestion? {
метод назови getSuggestions

2020-05-01 23:27 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/primainform/MerchantSuggestion.kt
> +class MerchantSuggestion {
переименуй в MerchantSuggestions

2020-05-01 23:27 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/primainform/MerchantDataValueDto.kt
> +class MerchantDataValueDto {
переименуй  в MerchantSuggestion

2020-05-01 23:27 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/primainform/MerchantDataValueDto.kt
> +    lateinit var value: String
по имени переменной не понятно что это за значение
напиши джавадок какая информация здесь хранится

2020-05-01 23:27 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/primainform/MerchantDataDto.kt
> +open class MerchantDataDto {
MerhcantInfo

2020-05-01 23:33 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/MerchantWebclient.kt
> +class MerchantWebclient {
исправил

2020-05-01 23:33 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/MerchantWebclient.kt
> +    fun getMerchantFromPrimaInformOrNone(inn: String): MerchantSuggestion? {
исправил

2020-05-01 23:34 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/primainform/MerchantSuggestion.kt
> +class MerchantSuggestion {
исправил

2020-05-01 23:34 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/primainform/MerchantDataValueDto.kt
> +class MerchantDataValueDto {
исправил

2020-05-01 23:34 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/primainform/MerchantDataDto.kt
> +open class MerchantDataDto {
исправил

2020-05-02 18:29 UTC, vladimirshefer requested changes

2020-05-02 18:29 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/service/MerchantService.kt
> +        return suggestion?.getSuggestions(inn)
я говорил "сервис долженуметь по инн возвращать мерчанта который подходит на 100%, либо null если такой не найден"

у тебя получается он возвращает всех которые вернулись 1к1
даже тех у которых по инн нет совпадения

2020-05-02 18:29 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/service/MerchantService.kt
> +        return suggestion?.getSuggestions(inn)
можешь попросить подсказку

2020-05-02 18:29 UTC, vladimirshefer commented on fns-sdk/src/test/kotlin/space/shefer/receipt/fnssdk/service/MerchantDtoTest.kt
> +        val json = "{\"suggestions\":[{\"value\":\"ООО \\\"ЛЕНТА\\\"\",\"data\":{\"inn\":\"7814148471\",\"permalink\":\"lenta-1037832048605-7814148471\",\"ogrn\":\"1037832048605\",\"address\":\"19737
https://kotlinlang.org/docs/reference/basic-types.html#string-literals
сможешь такое применить?

2020-05-02 18:29 UTC, vladimirshefer commented on fns-sdk/src/test/kotlin/space/shefer/receipt/fnssdk/service/MerchantDtoTest.kt
> +        TestCase.assertEquals("ООО \"ЛЕНТА\"", merchantSuggestions.suggestions.get(0).value)
опционально: Статический импорт

2020-05-02 18:29 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/service/MerchantService.kt
> +    lateinit var merchantSuggestions: PrimaInformWebClient
имя не подходит

2020-05-02 18:29 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/primainform/MerchantSuggestion.kt
> + * Data contains  inn, permalink, ogrn, address
ну у data и так есть эти поля, это понятно

2020-05-02 18:29 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/primainform/MerchantSuggestion.kt
> + * Value is name of organization
это джавадок над полем нужен а не над классом

2020-05-02 18:57 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/primainform/MerchantSuggestion.kt
> + * Value is name of organization
переделал

2020-05-02 18:57 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/primainform/MerchantSuggestion.kt
> + * Data contains  inn, permalink, ogrn, address
переделал

2020-05-02 18:58 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/service/MerchantService.kt
> +    lateinit var merchantSuggestions: PrimaInformWebClient
переделал

2020-05-02 18:58 UTC, VladNesterov commented on fns-sdk/src/test/kotlin/space/shefer/receipt/fnssdk/service/MerchantDtoTest.kt
> +        TestCase.assertEquals("ООО \"ЛЕНТА\"", merchantSuggestions.suggestions.get(0).value)
не понял

2020-05-02 18:58 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/service/MerchantService.kt
> +        return suggestion?.getSuggestions(inn)
не надо, переделал

2020-05-02 20:52 UTC, vladimirshefer requested changes

2020-05-02 20:52 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/primainform/MerchantSuggestion.kt
> +    //Value is name of organization
опционально: заменить просто коммент на джавадок

2020-05-02 20:52 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/PrimaInformWebClient.kt
> +                HttpEntity<String>(""),
а есть там что-то типа HttpEntity.empty() ?

2020-05-02 20:52 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/service/MerchantService.kt
> +        filteredSuggestions?.suggestions = primaInformWebClient.getSuggestions(inn)?.suggestions?.filter { it.data.inn == inn }!!
слишком длинная строчка

2020-05-02 20:52 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/service/MerchantService.kt
> +        filteredSuggestions?.suggestions = primaInformWebClient.getSuggestions(inn)?.suggestions?.filter { it.data.inn == inn }!!
зачем тут `!!`
`!!` ставится только если ты уверен что тут не может быть null, а он может быть

2020-05-02 21:28 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/PrimaInformWebClient.kt
> +                HttpEntity<String>(""),
![image](https://user-images.githubusercontent.com/23248545/80892727-ffc0c400-8cd4-11ea-94ae-28f70cb5e38e.png)

HttpEntity.EMPTY походу

2020-05-02 21:34 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/PrimaInformWebClient.kt
> +                HttpEntity<String>(""),
уже исправил

2020-05-02 21:34 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/primainform/MerchantSuggestion.kt
> +    //Value is name of organization
испрапвил

2020-05-02 21:34 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/service/MerchantService.kt
> +        filteredSuggestions?.suggestions = primaInformWebClient.getSuggestions(inn)?.suggestions?.filter { it.data.inn == inn }!!
поправил

2020-05-03 14:47 UTC, vladimirshefer requested changes

2020-05-03 14:47 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/service/MerchantService.kt
> +        return primaInformWebClient.getSuggestions(inn)?.suggestions?.filter { it.data.inn == inn }?.first()
это если после фильтра в итоговом листе не будет ни одного элемента, то бросится исключение, потому что first требует чтобы хотя бы один элемент был
```
.filter { it.data.inn == inn }?.first()
```

тебе нужно 
`find { it.data.inn == inn }` или `firstOrNull { it.data.inn == inn }`

2020-05-03 14:47 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/service/MerchantService.kt
> +        var filteredSuggestions: MerchantSuggestions? = null
эта переменная не используется

2020-05-03 14:47 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/service/MerchantService.kt
> +        return primaInformWebClient.getSuggestions(inn)?.suggestions?.filter { it.data.inn == inn }?.first()
слишком длинная строчка
сделай вызов каждого метода с кновой строчки
типа такого:
```
primaInformWebClient.getSuggestions(inn)
    ?.suggestions
    ?.filter { it.data.inn == inn }
    ?.first()
```

2020-05-03 15:38 UTC, vladimirshefer approved these changes

2020-05-03 15:53 UTC, merged