Добавить эндпоинт для удаления чека
receipt-project/receipt-java pull request #42
Opened 2020-05-05 17:39 UTC by VladNesterov

2020-05-05 22:36 UTC, vladimirshefer requested changes

2020-05-05 22:36 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/controller/ReceiptDeleteController.java
> +  public void delete(long id) {
на параметр нужно повесить аннотацию @RequestParam

2020-05-05 22:36 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/controller/ReceiptDeleteController.java
> +  @RequestMapping(value = "/delete", method = RequestMethod.POST)
Метод DELETE

2020-05-05 22:36 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/service/ReceiptService.java
> +      else {
тут кстати else можно опустить

2020-05-06 15:58 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/controller/ReceiptDeleteController.java
> +  public void delete(long id) {
done

2020-05-06 15:58 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/controller/ReceiptDeleteController.java
> +  @RequestMapping(value = "/delete", method = RequestMethod.POST)
done

2020-05-06 15:59 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/service/ReceiptService.java
> +      else {
done

2020-05-06 16:01 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/controller/ReceiptDeleteController.java
> +  public void delete(long id) {
Почему нам нужен @ RequestParam

2020-05-06 20:10 UTC, vladimirshefer approved these changes

2020-05-06 20:24 UTC, merged