/create возвращать статус чека #43
receipt-project/receipt-java pull request #44
Opened 2020-05-05 22:24 UTC by VladNesterov

2020-05-05 22:40 UTC, vladimirshefer requested changes

2020-05-05 22:40 UTC, vladimirshefer commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/ReceiptDeleteDto.java
> +  private ReceiptStatus status;
не, он не будет @Nullable

2020-05-05 22:40 UTC, vladimirshefer commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/ReceiptDeleteDto.java
> +public class ReceiptDeleteDto {
почему Delete а не Create?

2020-05-05 22:40 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/service/ReceiptService.java
>      Receipt savedReceipt = receiptRepository.save(entity);
делай return сразу всего savedReceipt, а преобразование в дто делай в контроллере

2020-05-05 22:40 UTC, vladimirshefer commented on README.md
> +  "status":"LOADED"
а почему ты сюда дописал?
это не тот метод и это вообще тело запроса, а ты менял структуру ответа

2020-05-05 22:41 UTC, vladimirshefer commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/ReceiptDeleteDto.java
> +public class ReceiptDeleteDto {
ты же создаешь чек а не удаляешь в этом методе

2020-05-06 16:01 UTC, VladNesterov commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/ReceiptDeleteDto.java
> +  private ReceiptStatus status;
done

2020-05-06 16:01 UTC, VladNesterov commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/ReceiptDeleteDto.java
> +public class ReceiptDeleteDto {
поменял

2020-05-06 16:02 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/service/ReceiptService.java
>      Receipt savedReceipt = receiptRepository.save(entity);
done

2020-05-06 16:02 UTC, VladNesterov commented on README.md
> +  "status":"LOADED"
поменял

2020-05-06 20:13 UTC, vladimirshefer requested changes

2020-05-06 20:13 UTC, vladimirshefer commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/ReceiptCreateNewFormatDto.java
> +public class ReceiptCreateNewFormatDto {
Я бы назвал ReceiptCreateResponseDto

2020-05-06 20:13 UTC, vladimirshefer commented on README.md
> +### Create
Смотри внимательно, документация для метода  create уже есть в этом файле

2020-05-06 20:24 UTC, VladNesterov commented on README.md
> +### Create
done

2020-05-06 20:25 UTC, VladNesterov commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/ReceiptCreateNewFormatDto.java
> +public class ReceiptCreateNewFormatDto {
done

2020-05-07 10:52 UTC, vladimirshefer requested changes

2020-05-07 10:52 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/controller/ReceiptCreateResponseDto.java
> +public class ReceiptCreateResponseDto {
кого ты переименовал? лол?
классом ошибся?)

2020-05-07 16:04 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/controller/ReceiptCreateResponseDto.java
> +public class ReceiptCreateResponseDto {
случайности)

2020-05-08 20:04 UTC, vladimirshefer approved these changes

2020-05-09 21:32 UTC, merged