Image for place
receipt-project/receipt-java pull request #55
Opened 2020-05-13 14:23 UTC by VladNesterov

2020-05-14 14:03 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/RestApplication.java
> -}
????

2020-05-14 14:03 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/service/ImagePlaceService.java
> +    List<String> catNames = new ArrayList<String>((Arrays.asList(namePlace.split(" "))));
когда делаешь Arrays.asList, то ты уже получаешь лист.
создавать из этого листа новый (копию) с посощью new ArrayList<>() - уже лишнее

```
List<String> catNames = (Arrays.asList(namePlace.split(" ")));
```

2020-05-14 15:26 UTC, vladimirshefer requested changes

2020-05-14 15:26 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/service/ImagePlaceService.java
> +public class ImagePlaceService {
MerchantLogoService

2020-05-14 15:26 UTC, vladimirshefer commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/ReceiptImagePlace.java
> +public enum ReceiptImagePlace {
MerchantSimpleName

2020-05-14 15:26 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/service/ImagePlaceService.java
> +    return storesAndImages;
ссфлки на картинки можно указать в поле енама
пример:
![image](https://user-images.githubusercontent.com/23248545/81953526-71233f80-9610-11ea-9a11-c483c0af99a4.png)

2020-05-15 22:03 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/RestApplication.java
> -}
исправил

2020-05-15 22:03 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/service/ImagePlaceService.java
> +    List<String> catNames = new ArrayList<String>((Arrays.asList(namePlace.split(" "))));
исправил

2020-05-15 22:03 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/service/ImagePlaceService.java
> +public class ImagePlaceService {
исправил

2020-05-15 22:03 UTC, VladNesterov commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/ReceiptImagePlace.java
> +public enum ReceiptImagePlace {
исправил

2020-05-15 22:03 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/service/ImagePlaceService.java
> +    return storesAndImages;
исправил

2020-05-15 22:21 UTC, vladimirshefer requested changes

2020-05-15 22:21 UTC, vladimirshefer commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/MerchantSimpleName.java
> +  private final String url;
logoUrl

2020-05-15 22:21 UTC, vladimirshefer commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/MerchantSimpleName.java
> +  MerchantSimpleName(String value,String url) {
logoUrl

2020-05-15 22:21 UTC, vladimirshefer commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/ReceiptMetaDto.java
> +  private String MerchantImageUrl;
с большой буквы

2020-05-15 22:21 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/service/MerchantLogoService.java
> +  }
опять мейн

2020-05-15 22:21 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/service/ReceiptService.java
> +      .peek(setUrl -> setUrl.setMerchantImageUrl(merchantLogoService.getUrlForImagePlace(setUrl.getPlace())))
имя параметра не соответствует типу

2020-05-15 22:21 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/service/MerchantLogoService.java
> +    return url;
url = Stream.of(MerchantSimpleName.values())
        .....
        .map(...)
        .orElse(null);

    return url;

2020-05-15 22:21 UTC, vladimirshefer commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/ReceiptMetaDto.java
> +  private String MerchantImageUrl;
merchantLogoUrl

2020-05-15 22:55 UTC, VladNesterov commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/MerchantSimpleName.java
> +  private final String url;
исправил

2020-05-15 22:55 UTC, VladNesterov commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/MerchantSimpleName.java
> +  MerchantSimpleName(String value,String url) {
испраил

2020-05-15 22:55 UTC, VladNesterov commented on rest-api-dto/src/main/java/space/shefer/receipt/rest/dto/ReceiptMetaDto.java
> +  private String MerchantImageUrl;
исправил

2020-05-15 22:55 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/service/MerchantLogoService.java
> +  }
убрал

2020-05-15 22:55 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/service/MerchantLogoService.java
> +    return url;
исправил

2020-05-16 01:56 UTC, vladimirshefer requested changes

2020-05-16 01:56 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/service/MerchantLogoService.java
> +      .filter(merchant -> merchant.getValue().contains(namePlace.toUpperCase()))
наоборот, название магазина содержит имя бренда, а не наоборот

2020-05-16 01:56 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/service/MerchantLogoService.java
> +  public String getUrlForImagePlace(String namePlace) {
getMerchantLogoUrl(String merchantFullName)

2020-05-16 01:56 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/service/ReceiptService.java
> +      .peek(receipt->receipt.setMerchantImageUrl(merchantLogoService.getUrlForImagePlace(receipt.getPlace())))
пробулы вокруг стрелочки

2020-05-21 21:37 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/service/ReceiptService.java
> +      .peek(setUrl -> setUrl.setMerchantImageUrl(merchantLogoService.getUrlForImagePlace(setUrl.getPlace())))
переделал

2020-05-21 21:37 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/service/MerchantLogoService.java
> +      .filter(merchant -> merchant.getValue().contains(namePlace.toUpperCase()))
переделал

2020-05-21 21:37 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/service/MerchantLogoService.java
> +  public String getUrlForImagePlace(String namePlace) {
переделал

2020-05-21 21:37 UTC, VladNesterov commented on rest-api/src/main/java/space/shefer/receipt/rest/service/ReceiptService.java
> +      .peek(receipt->receipt.setMerchantImageUrl(merchantLogoService.getUrlForImagePlace(receipt.getPlace())))
переделал

2020-05-23 18:20 UTC, vladimirshefer approved these changes

2020-05-23 23:28 UTC, vladimirshefer approved these changes

2020-05-24 23:16 UTC, merged