RCJ-55 Add login, authorization and recoveryPassword
receipt-project/receipt-java pull request #56
Opened 2020-05-24 23:13 UTC by VladNesterov

…troller and userDto

2020-05-25 13:27 UTC, vladimirshefer requested changes

2020-05-25 13:27 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/FnsReceiptWebClient.kt
> +                URI("https://proverkacheka.nalog.ru:9999/v1/mobile/users/login"),
переиспользуй переменную HOST со 111 строки

2020-05-25 13:27 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/FnsReceiptWebClient.kt
> +                    URI("https://proverkacheka.nalog.ru:9999/v1/mobile/users/signup"),
переиспользуй переменную HOST со 111 строки

2020-05-25 13:27 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/FnsReceiptWebClient.kt
> +                URI("https://proverkacheka.nalog.ru:9999/v1/mobile/users/restore"),
переиспользуй переменную HOST со 111 строки

2020-05-25 13:27 UTC, vladimirshefer commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/FnsReceiptWebClient.kt
> +                    HttpEntity("{\"email\":\"$email\",\"name\":\"$name\",\"phone\":\"$phone\"}", headers),
если это котлин то используй `""" """` строки чтобы не приходилось экранировать кавычки каждый раз
и в других методах тоже

2020-05-26 16:27 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/FnsReceiptWebClient.kt
> +                URI("https://proverkacheka.nalog.ru:9999/v1/mobile/users/login"),
переделал

2020-05-26 16:28 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/FnsReceiptWebClient.kt
> +                    URI("https://proverkacheka.nalog.ru:9999/v1/mobile/users/signup"),
переделал

2020-05-26 16:28 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/FnsReceiptWebClient.kt
> +                URI("https://proverkacheka.nalog.ru:9999/v1/mobile/users/restore"),
переделал

2020-05-26 16:28 UTC, VladNesterov commented on fns-sdk/src/main/kotlin/space/shefer/receipt/fnssdk/webclient/FnsReceiptWebClient.kt
> +                    HttpEntity("{\"email\":\"$email\",\"name\":\"$name\",\"phone\":\"$phone\"}", headers),
переделал

2020-05-27 16:00 UTC, vladimirshefer requested changes

2020-05-27 16:00 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/controller/UserController.java
> +  }
GET запросы не могут содержать тело (@RequestBody)
либо сделай POST, либо сделай @RequestParam-параметры (которые будут в урле передаваться)

2020-05-27 16:00 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/controller/UserController.java
> +  }
я бы предпочел POST, потому что передавать пароли в урле - плохая идея

2020-05-27 16:00 UTC, vladimirshefer commented on rest-api/src/main/java/space/shefer/receipt/rest/controller/UserController.java
> +  }
и сделай для каждого метода отдельную ДТОшку

ведь, например, для passwordRestore тебе нужен только номер телефона, а ты просишь еще и имя+пароль+почту и тд

2020-05-27 16:55 UTC, vladimirshefer approved these changes

2020-05-27 19:39 UTC, vladimirshefer requested changes

2020-05-27 19:39 UTC, vladimirshefer commented on README.md
> +### Execute actions with data user
### Login

2020-05-27 19:39 UTC, vladimirshefer commented on README.md
> +Если все хорошо, то вернется 200 OK и сообщение в виде json
в \`\`\` нужно обернуть только пример ответа
"Если все хорошо, то вернется 200 OK и сообщение в виде json" и прочий текст - часть описания ответа, нужно вынести за \`\`\`

2020-05-27 19:39 UTC, vladimirshefer commented on README.md
> +}
эта скобка здесь зачем?
удалить

2020-05-27 19:46 UTC, VladNesterov commented on README.md
> +### Execute actions with data user
поправил

2020-05-27 19:46 UTC, VladNesterov commented on README.md
> +Если все хорошо, то вернется 200 OK и сообщение в виде json
поправил

2020-05-27 19:46 UTC, VladNesterov commented on README.md
> +}
поправил

2020-05-27 20:26 UTC, vladimirshefer approved these changes

2020-05-28 06:27 UTC, VladNesterov commented
Fixes # 56

2020-05-28 06:28 UTC, merged