RCJ-74 Show correct message when you try to load receipts
receipt-project/receipt-java pull request #88
Opened 2020-06-12 15:56 UTC by VladNesterov

2020-06-12 16:04 UTC, vladimirshefer requested changes

2020-06-12 16:04 UTC, vladimirshefer commented on jobs/src/main/java/space/shefer/receipt/platform/jobs/ReceiptLoadJob.java
> +      .collect(Collectors.toList());
тут можно сразу .collect заменить на .count

2020-06-12 16:04 UTC, vladimirshefer commented on jobs/src/main/java/space/shefer/receipt/platform/jobs/ReceiptLoadJob.java
>          }
тут if тогда не нужен

2020-06-12 16:04 UTC, vladimirshefer commented on jobs/src/main/java/space/shefer/receipt/platform/jobs/ReceiptLoadJob.java
> +    System.out.println("Load attempts exceeded for " + receiptsFalseAttemptLoad.size() + " N receipts");
N это был плейсхолдер

2020-06-12 16:05 UTC, VladNesterov commented on jobs/src/main/java/space/shefer/receipt/platform/jobs/ReceiptLoadJob.java
> +    System.out.println("Load attempts exceeded for " + receiptsFalseAttemptLoad.size() + " N receipts");
уже заменил

2020-06-12 16:05 UTC, VladNesterov commented on jobs/src/main/java/space/shefer/receipt/platform/jobs/ReceiptLoadJob.java
>          }
убрал

2020-06-12 16:14 UTC, VladNesterov commented on jobs/src/main/java/space/shefer/receipt/platform/jobs/ReceiptLoadJob.java
> +      .collect(Collectors.toList());
заменил

2020-06-13 13:50 UTC, vladimirshefer approved these changes

2020-06-13 16:56 UTC, merged